============================= test session starts ==============================
platform linux -- Python 3.11.8, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/runner/work/Assessment-Backend-Week-1/Assessment-Backend-Week-1
collected 85 items

days_api/test_api.py ..F.F.FF..F..........FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 60%]
FFFFFFFFF                                                                [ 70%]
days_api/test_date_functions.py .........................                [100%]

======================== 44 failed, 41 passed in 0.25s =========================
************* Module app
days_api/app.py:7:0: W0611: Unused Response imported from flask (unused-import)
days_api/app.py:9:0: W0611: Unused get_day_of_week_on imported from date_functions (unused-import)
************* Module date_functions
days_api/date_functions.py:13:8: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValueError('Unable to convert value to datetime.') from exc' (raise-missing-from)

------------------------------------------------------------------
Your code has been rated at 9.84/10 (previous run: 9.84/10, +0.00)

